import Link from "next/link";

export const metadata={title:"Returns, Refunds & Exchanges | GiftingGuru",description:"GiftingGuru return, refund, exchange and defective-product policy."};

export default function ReturnsPage(){return <main className="infopage legalpage">
  <Link href="/" className="back">← Back to GiftingGuru</Link><p className="legaleyebrow">Last updated: 20 September 2026</p><h1>Returns, Refunds & Exchanges</h1>
  <div className="legalnotice"><strong>Start here:</strong> Email <a href="mailto:hello@giftingguru.co.za">hello@giftingguru.co.za</a> with your order number, the item, the reason for return, and photos or video where the item is damaged, incorrect or defective. Please wait for return instructions before sending anything.</div>
  <h2>Quick guide</h2><div className="policytable"><div><strong>Change of mind</strong><span>Notify us within 7 days after delivery. The item must be unused, complete and in resalable condition. Return delivery is normally for your account.</span></div><div><strong>Wrong item or transit damage</strong><span>Notify us as soon as possible, preferably within 48 hours, with clear photos. We arrange the remedy where the claim is valid.</span></div><div><strong>Defective item</strong><span>Notify us promptly. Statutory remedies apply, including the six-month protection for qualifying defective goods under the Consumer Protection Act.</span></div><div><strong>Exchange</strong><span>Subject to eligibility and stock. Price differences and customer-responsible delivery charges must be settled before dispatch.</span></div></div>
  <h2>1. Change-of-mind returns</h2><p>For an eligible online purchase, you may notify us in writing within 7 days after receiving the item that you wish to cancel. The item must then be returned promptly, unused, undamaged, complete, and with its original packaging, manuals, accessories, warranty cards, seals and bundled items.</p><p>For a change-of-mind return, the reasonable cost and risk of sending the item back are normally yours. We may deduct a reasonable amount for missing parts, damage, excessive handling or diminished value where permitted by law. We do not charge a penalty merely for exercising a statutory cooling-off right.</p>
  <h2>2. Items that cannot be returned for change of mind</h2><p>Unless the item is defective, unsafe, incorrectly supplied, or applicable law says otherwise, we cannot accept a change-of-mind return of:</p><ul><li>earphones, earbuds, headphones or wearable items once hygienic seals have been broken or the item has been worn;</li><li>personal-care, grooming or hygiene products once opened or used;</li><li>software, licence keys, activation codes, digital goods, airtime or electronically delivered items once supplied or activated;</li><li>ink, toner, batteries and other sealed consumables once opened, installed or used;</li><li>memory cards or storage devices where sealed packaging has been opened, unless all customer data has been securely removed and a return is required by law;</li><li>customised, engraved, personalised, specially sourced or made-to-order goods;</li><li>clearance or open-box goods where the disclosed condition is the reason for the return;</li><li>items damaged through misuse, accidental damage, liquid, power surge, incorrect installation, unauthorised repair or modification;</li><li>items missing serial labels, packaging, accessories, promotional items or components.</li></ul>
  <h2>3. Incorrect, incomplete or damaged deliveries</h2><p>Check your order soon after delivery. If the parcel or product arrives damaged, incomplete, or different from what you ordered, contact us as soon as possible, preferably within 48 hours. Keep the product and all packaging and send clear photographs of the shipping label, outer packaging, damage and contents. The 48-hour request helps us raise a courier claim and does not remove rights that cannot lawfully be limited.</p>
  <h2>4. Defective goods and warranties</h2><p>If goods fail to meet the quality standards required by the Consumer Protection Act within six months after delivery, you may be entitled to return them and choose a repair, replacement or refund, subject to the Act and a reasonable assessment. After six months, any applicable manufacturer or supplier warranty may continue, usually on a repair-first basis and subject to its terms.</p><p>An assessment may be required to confirm the fault and rule out excluded causes such as physical damage, misuse, incompatible equipment, liquid ingress, unauthorised work or normal wear. Assessment does not remove your statutory rights. If a valid repair under the Act fails or the fault recurs within the applicable period, the further remedies provided by law apply.</p>
  <h2>5. Exchanges</h2><p>Eligible unused products may be exchanged subject to stock. If the replacement costs more, you pay the difference. If it costs less, the balance is refunded to the original payment method or handled as agreed. We cannot reserve replacement stock until the returned item has been received and approved.</p>
  <h2>6. Return process</h2><ol><li>Email <a href="mailto:hello@giftingguru.co.za">hello@giftingguru.co.za</a> with your order number and reason for return.</li><li>Include photos or video for damage, wrong-item or defect claims.</li><li>Wait for return authorisation and the correct return address or collection instructions.</li><li>Back up and erase personal data, remove account locks and passwords, and package the item securely.</li><li>Include all accessories and proof of purchase. Do not attach courier labels directly to retail packaging.</li></ol><p>GiftingGuru is not responsible for customer data left on returned devices. We may refuse delivery of unapproved cash-on-delivery parcels.</p>
  <h2>7. Refund timing</h2><p>Once a return is received and approved, we will initiate the refund to the original payment method. Bank and payment-provider processing times are outside our control. Where a statutory cooling-off right applies, refunds are handled within the period required by law. Original delivery fees are refunded where required by law or where we supplied the wrong, damaged or defective item; otherwise they may be non-refundable.</p>
  <h2>8. Gifts and proof of purchase</h2><p>We need the order number or other reasonable proof of purchase. Refunds normally go to the original payer and payment method. A gift recipient may request an eligible exchange, but we may need authorisation from the purchaser for a refund.</p><p className="legalsmall">This policy supplements and does not replace rights that apply under South African consumer law.</p>
  <Link href="/#shop" className="infocta">Continue shopping</Link>
</main>}
